### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by abdol** [pankajbadatia/Crowd-density-monitoring-gui#1]
Hello,
Could you share the datasets used in this repo? 

When I run the program, I get the following error: 

FileNotFoundError: [Errno 2] No such file or directory: '/media/pankaj/D04BA26478DAA96B/PANKAJ/jointcnn/CNN 5 Cameras 5 Images lr 1e-5 y2018m05d04h11m41s21/discriminator model 1000000'

Thanks in Advance.

**Comment by pankajbadatia** [comment]
Hi I cannot share dataset, with you please mail it to xierong@sjtu.edu.cn for world expo dataset 10 .  you will have to fill some form. I don't own dataset.
